//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public string Title { get; set; }
        public string Name { get; set; }
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string PizzaName { get; set; }
        public decimal PizzaPrice { get; set; }
        public string SizeOfPizza { get; set; }
        public decimal percentage { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Flavour { get; set; }
        public decimal Add { get; set; }
        public string Delivery { get; set; }
        public string Expr1 { get; set; }
        public string DeliveryAddress { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string Surname { get; set; }
    }
}
